networks:
  univerHackathon.dev:
    name: server-internal-network
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: UniverHackathonDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - univerHackathon.dev

  backend:
    container_name: backend
    image: backend-univerhackathon
    build:
      context: .
      dockerfile: UniverHackathon.WebApi/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - univerHackathon.dev

volumes:
  postgres-data: